version: "3"

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: filaru
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
    expose:
      - '3306'
  app:
    container_name: appcontainer
    build: .
    image: nodeapp:filaru
    environment:
      - DB_HOST=mysqldb
    ports:
      - 3005:3005